#! /usr/bin/env python

import time
import sys
import xerox

if __name__ == "__main__":
    if len(sys.argv) == 1:
        print "Please supply an euler problem number as an parameter"
        exit()

    num = int(sys.argv[1])

    func_name = "euler%d" % num
    module = __import__(func_name, globals(), locals(), [func_name], -1)

    start = time.time()
    ans = getattr(module, func_name)()
    print ans
    #copy the answer to the clipboard
    xerox.copy(str(ans))
    print "%.6fs elapsed" % (time.time() - start)
